version: "3.9"

services:
    api:
      build:
        context: .
        dockerfile: Dockerfile
      container_name: mlops_api
      ports: 
        - "8000:80"
      volumes:
        - "./model:/app/model"
      environment:
        - PYTHONUNBUFFERED=1
      restart: unless-stopped
